[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"
    Cache-Control = "no-store"

[template.environment]
  EMAIL_CONFIRM_PATH = "/admin"
  INVITE_PATH = "/admin"
